name: Deploy

on: 
  push:
    branches: 
      - src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true
