name: Deploy

on: 
  push:
    branches: 
      - src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build --if-present
      
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.0.1
      with:
        personal_token: ${{ secrets.GITHUB_PAT }}
        publish_branch: master
        publish_dir: public
        force_orphan: true
