name: Deploy

on:
  push:
    branches:
      - src

jobs:
  build:

    

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g yarn
    - run: yarn
    - run: yarn run build

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.0.1
      with:
        personal_token: ${{ secrets.GITHUB_PAT }}
        publish_branch: master
        publish_dir: public
        # force_orphan: true
